version: 2
jobs:
  build:
    docker:
      - image: node:10
      - image: vvoyer/selenium-standalone
        name: selenium
        environment:
          HUB_PORT_4444_TCP_ADDR: hub
          HUB_PORT_4444_TCP_PORT: 4444
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run:
      #     command: npm run start
      #     background: true
        
      # run tests!
      - run: npm run test

      - store_artifacts:
          path: ./errorShots/
          when: always